apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 534969654347.dkr.ecr.us-east-1.amazonaws.com/clo835-assgn2-repo:mysql-v1
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pw
    - name: MYSQL_DATABASE
      value: employees
    ports:
    - containerPort: 3306


