apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
      - name: my-ecr-secret
      containers:
      - name: webapp
        image: 534969654347.dkr.ecr.us-east-1.amazonaws.com/clo835-assgn2-repo:webapp-v1
        env:
        - name: DBHOST
          value: "10.244.0.5"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: pw
        - name: DATABASE
          value: employees
        - name: APP_COLOR
          value: blue
        ports:
        - containerPort: 8080
