name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 534969654347.dkr.ecr.us-east-1.amazonaws.com/clo835.assignment1

      - name: Build MySQL Docker image
        run: |
          docker build -t mysql-image -f Dockerfile_mysql .
          docker tag mysql-image:latest 534969654347.dkr.ecr.us-east-1.amazonaws.com/clo835.assignment1:mysql

      - name: Build Web App Docker image
        run: |
          docker build -t webapp-image -f Dockerfile .
          docker tag webapp-image:latest 534969654347.dkr.ecr.us-east-1.amazonaws.com/clo835.assignment1:webapp

      - name: Push MySQL Docker image to ECR
        run: |
          docker push 534969654347.dkr.ecr.us-east-1.amazonaws.com/clo835.assignment1:mysql

      - name: Push Web App Docker image to ECR
        run: |
          docker push 534969654347.dkr.ecr.us-east-1.amazonaws.com/clo835.assignment1:webapp
